# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19DyStxHIIsfGegPhcA4s9aMm54J864Kn
"""

num=int(input("enter a number:"))
if num%2==0:
  print(num,"is even")
else:
  print(num,"is odd")